In [7]:
#点击run显示pycharm please,enter your authentication token  在Run输出栏输入token，记住只输入token

import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data 
import os
import sys

print(sys.path)

#one_hot=True 意思是只有一个元素为1，其余都是0
mnist = input_data.read_data_sets("./MNIST_data/", one_hot=True)

os.environ["TF_CPP_MIN_LOG_LEVEL"]="3"
print(mnist.train.images.shape,mnist.train.labels.shape)
print(mnist.test.images.shape,mnist.test.labels.shape)
#validation 验证
print(mnist.validation.images.shape,mnist.validation.labels.shape)

#创建一个session，之后运算都跑到这个默认的session里
sess = tf.InteractiveSession();
x = tf.placeholder(tf.float32,[None,784])

W = tf.Variable(tf.zeros([784,10]))
b = tf.Variable(tf.zeros([10]))
y = tf.nn.softmax(tf.matmul(x,W)+b)
y_= tf.placeholder(tf.float32,[None,10])



#"理解reduce和axis:"
#总结，越外面的axis越小，每往里面进一个括号，axis就加1. 在某一层的axis,看同维度矩阵相加。如下面axis=3.找到axis=3的维度的元素，相加[1+2,3+4][3+4,5+6][]
#axis=0 那么找到维度为axis=1的维度的元素 [[[1,2],[3,4]]]  [[[3,4],[5,6]]]  [[[1,0],[0,0]]]  [[[0,0],[0,0]]]内部相加，那么就是
#[[[1+3+1+0,2+4+0+0],[3+5+0+0,4+6+0+0]]]

#在IDE中的使用方式：对于一个n维矩阵，当axis=n-i时，从最外层的括号中向里面进i个括号，该括号中并列的元素就是该axis=n-i的元素，将所有
# 并列的所有元素相加，得到的就是新组成的矩阵。
#keepdims指的是保持该矩阵维度不变进行  axis变换。不掉一层括号（不掉被塌方（reduce）那一层的括号）
a = [[[[1,2],[3,4]]],[[[3,4],[5,6]]],[[[1,0],[0,0]]],[[[0,0],[0,0]]]]
a0 = tf.reduce_sum(a, axis=0)
a0.shape
#print(a0.shape)
#print(tf.reduce_sum(a, axis=1,keepdims=True))
#print(tf.reduce_sum(a, axis=2))
#print(tf.reduce_sum(a, axis=3))
print("---------------------")
print(sess.run(a0))
print("---------------------")
print(sess.run(tf.reduce_sum(a, axis=1)))
print("---------------------")
print(sess.run(tf.reduce_sum(a, axis=2)))
print("---------------------")
print(sess.run(tf.reduce_sum(a, axis=3)))











['', 'D:\\PythonProject', 'C:\\Users\\27154\\AppData\\Local\\Programs\\Python\\Python36\\python36.zip', 'C:\\Users\\27154\\AppData\\Local\\Programs\\Python\\Python36\\DLLs', 'C:\\Users\\27154\\AppData\\Local\\Programs\\Python\\Python36\\lib', 'C:\\Users\\27154\\AppData\\Local\\Programs\\Python\\Python36', 'C:\\Users\\27154\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages', 'C:\\Users\\27154\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\IPython\\extensions', 'C:\\Users\\27154\\.ipython']
Extracting ./MNIST_data/train-images-idx3-ubyte.gz


Extracting ./MNIST_data/train-labels-idx1-ubyte.gz
Extracting ./MNIST_data/t10k-images-idx3-ubyte.gz
Extracting ./MNIST_data/t10k-labels-idx1-ubyte.gz


(55000, 784) (55000, 10)
(10000, 784) (10000, 10)
(5000, 784) (5000, 10)


C:\Users\27154\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py:1711: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


---------------------
[[[ 5  6]
  [ 8 10]]]
---------------------
[[[1 2]
  [3 4]]

 [[3 4]
  [5 6]]

 [[1 0]
  [0 0]]

 [[0 0]
  [0 0]]]
---------------------
[[[ 4  6]]

 [[ 8 10]]

 [[ 1  0]]

 [[ 0  0]]]
---------------------
[[[ 3  7]]

 [[ 7 11]]

 [[ 1  0]]

 [[ 0  0]]]


In [11]:

#reduce_sum() 就是求和，由于求和的对象是tensor，所以是沿着tensor的某些维度求和。
#reduction_indices是指沿tensor的哪些维度求和。
#tf.reduce_mean求平均值
    #tf.reduce_mean(x) ==> 2.5 #如果不指定第二个参数，那么就在所有的元素中取平均值
    #tf.reduce_mean(x, 0) ==> [2.,  3.] #指定第二个参数为0，则第一维的元素取平均值，即每一列求平均值
    #tf.reduce_mean(x, 1) ==> [1.5,  3.5] #指定第二个参数为1，则第二维的元素取平均值，即每一行求平均值
cross_entropy = tf.reduce_mean(-tf.reduce_sum(y_*tf.log(y),reduction_indices=[1]))


#print(sess.run(cross_entropy))



print("测试，测试")

print("测试，测试")

print("测试，测试")

InvalidArgumentError: You must feed a value for placeholder tensor 'Placeholder_6' with dtype float and shape [?,784]
	 [[Node: Placeholder_6 = Placeholder[dtype=DT_FLOAT, shape=[?,784], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op 'Placeholder_6', defined at:
  File "C:\Users\27154\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\27154\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\27154\AppData\Local\Programs\Python\Python36\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "C:\Users\27154\AppData\Local\Programs\Python\Python36\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "C:\Users\27154\AppData\Local\Programs\Python\Python36\lib\site-packages\ipykernel\kernelapp.py", line 486, in start
    self.io_loop.start()
  File "C:\Users\27154\AppData\Local\Programs\Python\Python36\lib\site-packages\tornado\platform\asyncio.py", line 127, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\27154\AppData\Local\Programs\Python\Python36\lib\asyncio\base_events.py", line 421, in run_forever
    self._run_once()
  File "C:\Users\27154\AppData\Local\Programs\Python\Python36\lib\asyncio\base_events.py", line 1425, in _run_once
    handle._run()
  File "C:\Users\27154\AppData\Local\Programs\Python\Python36\lib\asyncio\events.py", line 126, in _run
    self._callback(*self._args)
  File "C:\Users\27154\AppData\Local\Programs\Python\Python36\lib\site-packages\tornado\platform\asyncio.py", line 117, in _handle_events
    handler_func(fileobj, events)
  File "C:\Users\27154\AppData\Local\Programs\Python\Python36\lib\site-packages\tornado\stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\Users\27154\AppData\Local\Programs\Python\Python36\lib\site-packages\zmq\eventloop\zmqstream.py", line 450, in _handle_events
    self._handle_recv()
  File "C:\Users\27154\AppData\Local\Programs\Python\Python36\lib\site-packages\zmq\eventloop\zmqstream.py", line 480, in _handle_recv
    self._run_callback(callback, msg)
  File "C:\Users\27154\AppData\Local\Programs\Python\Python36\lib\site-packages\zmq\eventloop\zmqstream.py", line 432, in _run_callback
    callback(*args, **kwargs)
  File "C:\Users\27154\AppData\Local\Programs\Python\Python36\lib\site-packages\tornado\stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\Users\27154\AppData\Local\Programs\Python\Python36\lib\site-packages\ipykernel\kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "C:\Users\27154\AppData\Local\Programs\Python\Python36\lib\site-packages\ipykernel\kernelbase.py", line 233, in dispatch_shell
    handler(stream, idents, msg)
  File "C:\Users\27154\AppData\Local\Programs\Python\Python36\lib\site-packages\ipykernel\kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "C:\Users\27154\AppData\Local\Programs\Python\Python36\lib\site-packages\ipykernel\ipkernel.py", line 208, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "C:\Users\27154\AppData\Local\Programs\Python\Python36\lib\site-packages\ipykernel\zmqshell.py", line 537, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "C:\Users\27154\AppData\Local\Programs\Python\Python36\lib\site-packages\IPython\core\interactiveshell.py", line 2662, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "C:\Users\27154\AppData\Local\Programs\Python\Python36\lib\site-packages\IPython\core\interactiveshell.py", line 2785, in _run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "C:\Users\27154\AppData\Local\Programs\Python\Python36\lib\site-packages\IPython\core\interactiveshell.py", line 2903, in run_ast_nodes
    if self.run_code(code, result):
  File "C:\Users\27154\AppData\Local\Programs\Python\Python36\lib\site-packages\IPython\core\interactiveshell.py", line 2963, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-7-612c5ccb9195>", line 21, in <module>
    x = tf.placeholder(tf.float32,[None,784])
  File "C:\Users\27154\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\ops\array_ops.py", line 1808, in placeholder
    return gen_array_ops.placeholder(dtype=dtype, shape=shape, name=name)
  File "C:\Users\27154\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 5835, in placeholder
    "Placeholder", dtype=dtype, shape=shape, name=name)
  File "C:\Users\27154\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\27154\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 3392, in create_op
    op_def=op_def)
  File "C:\Users\27154\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'Placeholder_6' with dtype float and shape [?,784]
	 [[Node: Placeholder_6 = Placeholder[dtype=DT_FLOAT, shape=[?,784], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
